### ISSUE TITLE
Several errors while trying to install Clarifai API Python Client

### ISSUE THREAD

**Issue by Sepehr2016** [Clarifai/clarifai-python#51] opened 2017-03-24 20:43 UTC
I have Python 2.7.13 installed on Windows 7 64-bit, but each time I'm going to install Clarifai Python Client, I get various errors. Now stuck at the following error:
![error](https://cloud.githubusercontent.com/assets/16511601/24312855/2254c2ac-10f8-11e7-80ba-c4cc64299b32.png)
There are two folders named "setuptools-34.3.2.dist-info" and "setuptools" in C:\Python27\Lib\site-packages directory, also "clarifai-2.0.20.dist-info" and "clarifai", but I can't set my Clarifai credientals.

**Comment by robertwenquan** [comment] 2017-03-24 21:16
Hi @Sepehr2016 

Thanks for reaching out. There are a couple of issues you may want to address:

1. python client is now at v2.0.20
2. It is not the best practice to install from source. Please do `pip install clarifai`
3. It is more recommended to install the library in a virtualenv

**Comment by robertwenquan** [comment] 2017-03-25 04:34
Hi @Sepehr2016 ,

I believe this is not a bug. Please reach out to robert@clarifai.com if you still have issue. I am closing this issue.

**Closed by robertwenquan** 2017-03-25 04:34 UTC
