### ISSUE TITLE
Getting an error in python grpc client

### ISSUE THREAD

**Issue by reena-oommen** [Clarifai/clarifai-python#129] opened 2022-04-24 08:20 UTC
Family\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Makkouk Family\Desktop\All desktop folders\Python Level 4\Image Analyser - Tarek.py", line 40, in search
    response = stub.PostModelOutputs(my_request, metadata=metadata)
  File "C:\Users\Makkouk Family\AppData\Local\Programs\Python\Python39\lib\site-packages\clarifai_grpc\channel\grpc_json_channel.py", line 185, in __call__
    result = dict_to_protobuf(message, response_json, ignore_unknown_fields=True)
  File "C:\Users\Makkouk Family\AppData\Local\Programs\Python\Python39\lib\site-packages\clarifai_grpc\channel\custom_converters\custom_dict_to_message.py", line 25, in dict_to_protobuf
    parser.ConvertMessage(js_dict, message)
TypeError: ConvertMessage() missing 1 required positional argument: 'path'
127.0.0.1 - - [24/Apr/2022 10:20:38] " [35m [1mPOST / HTTP/1.1 [0m" 500 -

**Comment by moldovan-clarifai** [comment] 2022-04-25 07:18
Duplicate of https://github.com/Clarifai/clarifai-python-grpc/issues/66:

> Currently we do not support 3.20.0 yet. Please downgrade the protobuf to 3.19.4 for now till we upgrade our requirements.txt.

**Comment by yangshengBE** [comment] 2023-02-16 14:38
we have upgraded the protobuf in clarifai-python-grpc. Please try the new release.

**Closed by yangshengBE** 2023-02-16 14:38 UTC
